import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("telecom_kpi_balanced.csv")
print(df.head())
print(df.info())
print(df.isnull().sum())
print(df.describe())
print(df.columns)
avg_rsrp=df.groupby("Cell_ID")["RSRP"].mean()
print(avg_rsrp)
avg_rsrp.plot(kind="bar",figsize=(10,5))
plt.title("Average RSRP per Cell")
plt.ylabel("RSRP(dBm)")
plt.show()
avg_tp=df.groupby("Timestamp")["Throughput"].mean()
print(avg_tp)
avg_tp.plot(marker='o')
plt.title("Average Throughput per Hour")
plt.ylabel("Mbps")
plt.show()
peak_hour=df.groupby("Timestamp")["Connected_Users"].mean()
print(peak_hour)
print("Peak Hour:",peak_hour.idxmax())
worst_cells=df.groupby("Cell_ID").agg({"SINR":"mean","Latency":"mean","Packet_Loss":"mean"})
print(worst_cells)
bad_cells=worst_cells[(worst_cells["SINR"]<10) | (worst_cells["Latency"]>50) | (worst_cells["Packet_Loss"]>3)]
print(bad_cells)
plt.figure(figsize=(8,6))
sns.heatmap(df[["RSRP","SINR","Latency","Packet_Loss","Throughput","Connected_Users"]].corr(),annot=True,cmap="coolwarm")
plt.show()
plt.figure(figsize=(8,5))
plt.scatter(df["SINR"],df["Throughput"])
plt.xlabel("SINR")
plt.ylabel("Throughput")
plt.show()
plt.hist(df["RSRP"],bins=20)
plt.xlabel("RSRP")
plt.ylabel("Frequency")
plt.show()
avg_rsrp.to_csv("average_rsrp.csv")
avg_tp.to_csv("average_throughput.csv")
bad_cells.to_csv("worst_cells.csv")